[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "5Dy4o72t49Mvv9nQbajT8EhLuyfXafAzQcANnEDczZMS"
[programs.devnet]
solana_twitter = "5Dy4o72t49Mvv9nQbajT8EhLuyfXafAzQcANnEDczZMS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jdunn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"

