[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "5Dy4o72t49Mvv9nQbajT8EhLuyfXafAzQcANnEDczZMS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jdunn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
